{"name": "User can verify the products in cart", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"div.h-margin-l-x2 span\"}\n  (Session info: chrome=128.0.6613.138); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x007CD933+25811]\n\t(No symbol) [0x0075E314]\n\t(No symbol) [0x00652523]\n\t(No symbol) [0x00697483]\n\t(No symbol) [0x0069765B]\n\t(No symbol) [0x006D6BA2]\n\t(No symbol) [0x006BAD74]\n\t(No symbol) [0x006D46F0]\n\t(No symbol) [0x006BAAC6]\n\t(No symbol) [0x0068BEFD]\n\t(No symbol) [0x0068C8FD]\n\tGetHandleVerifier [0x00A9F143+2981091]\n\tGetHandleVerifier [0x00AF2FF9+3324825]\n\tGetHandleVerifier [0x0085B32F+605903]\n\tGetHandleVerifier [0x00862CBC+637020]\n\t(No symbol) [0x00766F4D]\n\t(No symbol) [0x00763DD8]\n\t(No symbol) [0x00763F75]\n\t(No symbol) [0x00756406]\n\tBaseThreadInitThunk [0x758D7BA9+25]\n\tRtlInitializeExceptionChain [0x77C8C11B+107]\n\tRtlClearBits [0x77C8C09F+191]\n\n", "trace": "  File \"C:\\Users\\Admin\\python-selenium-automation-2024\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Admin\\python-selenium-automation-2024\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\cart_page.py\", line 53, in number_and_price_of_products\n    context.app.checkout_page.verify_product()\n  File \"C:\\Users\\Admin\\python-selenium-automation-2024\\pages\\checkout_page.py\", line 17, in verify_product\n    items = self.driver.find_element(*self.CART).text\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\python-selenium-automation-2024\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\python-selenium-automation-2024\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Admin\\python-selenium-automation-2024\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Open Target page", "status": "passed", "start": 1728680898205, "stop": 1728680901831}, {"name": "When Search for an tea", "status": "passed", "start": 1728680901831, "stop": 1728680919458}, {"name": "And Add items into cart", "status": "passed", "start": 1728680919458, "stop": 1728680934127}, {"name": "Then Verify the products", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"div.h-margin-l-x2 span\"}\n  (Session info: chrome=128.0.6613.138); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x007CD933+25811]\n\t(No symbol) [0x0075E314]\n\t(No symbol) [0x00652523]\n\t(No symbol) [0x00697483]\n\t(No symbol) [0x0069765B]\n\t(No symbol) [0x006D6BA2]\n\t(No symbol) [0x006BAD74]\n\t(No symbol) [0x006D46F0]\n\t(No symbol) [0x006BAAC6]\n\t(No symbol) [0x0068BEFD]\n\t(No symbol) [0x0068C8FD]\n\tGetHandleVerifier [0x00A9F143+2981091]\n\tGetHandleVerifier [0x00AF2FF9+3324825]\n\tGetHandleVerifier [0x0085B32F+605903]\n\tGetHandleVerifier [0x00862CBC+637020]\n\t(No symbol) [0x00766F4D]\n\t(No symbol) [0x00763DD8]\n\t(No symbol) [0x00763F75]\n\t(No symbol) [0x00756406]\n\tBaseThreadInitThunk [0x758D7BA9+25]\n\tRtlInitializeExceptionChain [0x77C8C11B+107]\n\tRtlClearBits [0x77C8C09F+191]\n\n", "trace": "  File \"C:\\Users\\Admin\\python-selenium-automation-2024\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Admin\\python-selenium-automation-2024\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\cart_page.py\", line 53, in number_and_price_of_products\n    context.app.checkout_page.verify_product()\n  File \"C:\\Users\\Admin\\python-selenium-automation-2024\\pages\\checkout_page.py\", line 17, in verify_product\n    items = self.driver.find_element(*self.CART).text\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\python-selenium-automation-2024\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\python-selenium-automation-2024\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Admin\\python-selenium-automation-2024\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1728680934127, "stop": 1728680943209}], "start": 1728680896071, "stop": 1728680945457, "uuid": "3c156d7d-6531-49a8-a958-3b4511a19b3f", "historyId": "1f22bb4a4193044ebbba00a4ab1e4bda", "fullName": "Product checkout functionality: User can verify the products in cart", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Product checkout functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}